# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QDateEdit,
    QDoubleSpinBox, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QToolBar, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1045, 477)
        self.action_theme_light = QAction(MainWindow)
        self.action_theme_light.setObjectName(u"action_theme_light")
        self.action_theme_dark = QAction(MainWindow)
        self.action_theme_dark.setObjectName(u"action_theme_dark")
        self.action_theme_fusion = QAction(MainWindow)
        self.action_theme_fusion.setObjectName(u"action_theme_fusion")
        self.action_catalogue = QAction(MainWindow)
        self.action_catalogue.setObjectName(u"action_catalogue")
        self.action_catalogue.setCheckable(True)
        self.action_recipes = QAction(MainWindow)
        self.action_recipes.setObjectName(u"action_recipes")
        self.action_recipes.setCheckable(True)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.action_daily_intake = QAction(MainWindow)
        self.action_daily_intake.setObjectName(u"action_daily_intake")
        self.action_daily_intake.setCheckable(True)
        self.action_menubar_open = QAction(MainWindow)
        self.action_menubar_open.setObjectName(u"action_menubar_open")
        self.action_menubar_save = QAction(MainWindow)
        self.action_menubar_save.setObjectName(u"action_menubar_save")
        self.action_export_catalogue = QAction(MainWindow)
        self.action_export_catalogue.setObjectName(u"action_export_catalogue")
        self.action_import_catalogue = QAction(MainWindow)
        self.action_import_catalogue.setObjectName(u"action_import_catalogue")
        self.action_export_recipes = QAction(MainWindow)
        self.action_export_recipes.setObjectName(u"action_export_recipes")
        self.action_import_recipes = QAction(MainWindow)
        self.action_import_recipes.setObjectName(u"action_import_recipes")
        self.action_menubar_save_as = QAction(MainWindow)
        self.action_menubar_save_as.setObjectName(u"action_menubar_save_as")
        self.action_menubar_quit = QAction(MainWindow)
        self.action_menubar_quit.setObjectName(u"action_menubar_quit")
        self.action_export_daily_intake = QAction(MainWindow)
        self.action_export_daily_intake.setObjectName(u"action_export_daily_intake")
        self.action_import_daily_intake = QAction(MainWindow)
        self.action_import_daily_intake.setObjectName(u"action_import_daily_intake")
        self.action_import_Excel_catalogue = QAction(MainWindow)
        self.action_import_Excel_catalogue.setObjectName(u"action_import_Excel_catalogue")
        self.action_export_Excel_catalogue = QAction(MainWindow)
        self.action_export_Excel_catalogue.setObjectName(u"action_export_Excel_catalogue")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget_main = QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName(u"stackedWidget_main")
        self.page_daily_intake = QWidget()
        self.page_daily_intake.setObjectName(u"page_daily_intake")
        self.horizontalLayout_dashboard = QHBoxLayout(self.page_daily_intake)
        self.horizontalLayout_dashboard.setSpacing(0)
        self.horizontalLayout_dashboard.setObjectName(u"horizontalLayout_dashboard")
        self.horizontalLayout_dashboard.setContentsMargins(0, 0, 0, 0)
        self.frame_dashboard_left = QFrame(self.page_daily_intake)
        self.frame_dashboard_left.setObjectName(u"frame_dashboard_left")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_dashboard_left.sizePolicy().hasHeightForWidth())
        self.frame_dashboard_left.setSizePolicy(sizePolicy)
        self.frame_dashboard_left.setMinimumSize(QSize(0, 0))
        self.frame_dashboard_left.setMaximumSize(QSize(16777215, 16777215))
        self.frame_dashboard_left.setFrameShape(QFrame.NoFrame)
        self.frame_dashboard_left.setFrameShadow(QFrame.Plain)
        self.frame_dashboard_left.setLineWidth(0)
        self.verticalLayout_frame_dashboard_left = QVBoxLayout(self.frame_dashboard_left)
        self.verticalLayout_frame_dashboard_left.setSpacing(0)
        self.verticalLayout_frame_dashboard_left.setObjectName(u"verticalLayout_frame_dashboard_left")
        self.verticalLayout_frame_dashboard_left.setContentsMargins(0, 0, 0, 0)
        self.frame_totals_diagram = QFrame(self.frame_dashboard_left)
        self.frame_totals_diagram.setObjectName(u"frame_totals_diagram")
        self.frame_totals_diagram.setFrameShape(QFrame.NoFrame)
        self.frame_totals_diagram.setFrameShadow(QFrame.Plain)
        self.frame_totals_diagram.setLineWidth(0)
        self.verticalLayout_frame_totals_diagram = QVBoxLayout(self.frame_totals_diagram)
        self.verticalLayout_frame_totals_diagram.setSpacing(0)
        self.verticalLayout_frame_totals_diagram.setObjectName(u"verticalLayout_frame_totals_diagram")
        self.verticalLayout_frame_totals_diagram.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_frame_dashboard_left.addWidget(self.frame_totals_diagram)

        self.frame_nutrition_targets = QFrame(self.frame_dashboard_left)
        self.frame_nutrition_targets.setObjectName(u"frame_nutrition_targets")
        self.frame_nutrition_targets.setFrameShape(QFrame.NoFrame)
        self.frame_nutrition_targets.setFrameShadow(QFrame.Plain)
        self.frame_nutrition_targets.setLineWidth(0)
        self.verticalLayout_3 = QVBoxLayout(self.frame_nutrition_targets)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(9, 0, 0, 0)
        self.label_nutrition_targets = QLabel(self.frame_nutrition_targets)
        self.label_nutrition_targets.setObjectName(u"label_nutrition_targets")
        self.label_nutrition_targets.setTextFormat(Qt.RichText)

        self.verticalLayout_3.addWidget(self.label_nutrition_targets)


        self.verticalLayout_frame_dashboard_left.addWidget(self.frame_nutrition_targets)

        self.frame_intake_target = QFrame(self.frame_dashboard_left)
        self.frame_intake_target.setObjectName(u"frame_intake_target")
        self.frame_intake_target.setFrameShape(QFrame.NoFrame)
        self.frame_intake_target.setFrameShadow(QFrame.Plain)
        self.frame_intake_target.setLineWidth(0)
        self.horizontalLayout_frame_intake_target = QHBoxLayout(self.frame_intake_target)
        self.horizontalLayout_frame_intake_target.setObjectName(u"horizontalLayout_frame_intake_target")

        self.verticalLayout_frame_dashboard_left.addWidget(self.frame_intake_target)


        self.horizontalLayout_dashboard.addWidget(self.frame_dashboard_left)

        self.frame_dashboard_right = QFrame(self.page_daily_intake)
        self.frame_dashboard_right.setObjectName(u"frame_dashboard_right")
        sizePolicy.setHeightForWidth(self.frame_dashboard_right.sizePolicy().hasHeightForWidth())
        self.frame_dashboard_right.setSizePolicy(sizePolicy)
        self.frame_dashboard_right.setMinimumSize(QSize(0, 0))
        self.frame_dashboard_right.setFrameShape(QFrame.NoFrame)
        self.frame_dashboard_right.setFrameShadow(QFrame.Plain)
        self.frame_dashboard_right.setLineWidth(0)
        self.verticalLayout_frame_dashboard_right = QVBoxLayout(self.frame_dashboard_right)
        self.verticalLayout_frame_dashboard_right.setSpacing(0)
        self.verticalLayout_frame_dashboard_right.setObjectName(u"verticalLayout_frame_dashboard_right")
        self.verticalLayout_frame_dashboard_right.setContentsMargins(0, 0, 0, 0)
        self.frame_calendar = QFrame(self.frame_dashboard_right)
        self.frame_calendar.setObjectName(u"frame_calendar")
        self.frame_calendar.setMinimumSize(QSize(0, 50))
        self.frame_calendar.setFrameShape(QFrame.NoFrame)
        self.frame_calendar.setFrameShadow(QFrame.Plain)
        self.frame_calendar.setLineWidth(0)
        self.verticalLayout_frame_calendar = QVBoxLayout(self.frame_calendar)
        self.verticalLayout_frame_calendar.setSpacing(0)
        self.verticalLayout_frame_calendar.setObjectName(u"verticalLayout_frame_calendar")
        self.verticalLayout_frame_calendar.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_frame_dashboard_right.addWidget(self.frame_calendar)

        self.frame_daily_intake_buttons = QFrame(self.frame_dashboard_right)
        self.frame_daily_intake_buttons.setObjectName(u"frame_daily_intake_buttons")
        self.frame_daily_intake_buttons.setMinimumSize(QSize(0, 50))
        self.frame_daily_intake_buttons.setMaximumSize(QSize(16777215, 40))
        self.frame_daily_intake_buttons.setFrameShape(QFrame.NoFrame)
        self.frame_daily_intake_buttons.setFrameShadow(QFrame.Plain)
        self.frame_daily_intake_buttons.setLineWidth(0)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_daily_intake_buttons)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton_add_catalogue_item = QPushButton(self.frame_daily_intake_buttons)
        self.pushButton_add_catalogue_item.setObjectName(u"pushButton_add_catalogue_item")
        self.pushButton_add_catalogue_item.setMinimumSize(QSize(30, 30))
        self.pushButton_add_catalogue_item.setMaximumSize(QSize(30, 30))

        self.horizontalLayout_2.addWidget(self.pushButton_add_catalogue_item)

        self.pushButton_add_recipe_item = QPushButton(self.frame_daily_intake_buttons)
        self.pushButton_add_recipe_item.setObjectName(u"pushButton_add_recipe_item")
        self.pushButton_add_recipe_item.setMinimumSize(QSize(30, 30))
        self.pushButton_add_recipe_item.setMaximumSize(QSize(30, 30))

        self.horizontalLayout_2.addWidget(self.pushButton_add_recipe_item)

        self.pushButton_previous_date = QPushButton(self.frame_daily_intake_buttons)
        self.pushButton_previous_date.setObjectName(u"pushButton_previous_date")
        self.pushButton_previous_date.setMinimumSize(QSize(30, 30))
        self.pushButton_previous_date.setMaximumSize(QSize(30, 30))

        self.horizontalLayout_2.addWidget(self.pushButton_previous_date)

        self.dateEdit_daily_intake_date = QDateEdit(self.frame_daily_intake_buttons)
        self.dateEdit_daily_intake_date.setObjectName(u"dateEdit_daily_intake_date")
        self.dateEdit_daily_intake_date.setMinimumSize(QSize(120, 30))
        self.dateEdit_daily_intake_date.setMaximumSize(QSize(120, 16777215))
        self.dateEdit_daily_intake_date.setAlignment(Qt.AlignCenter)
        self.dateEdit_daily_intake_date.setReadOnly(True)
        self.dateEdit_daily_intake_date.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.dateEdit_daily_intake_date.setCalendarPopup(False)

        self.horizontalLayout_2.addWidget(self.dateEdit_daily_intake_date)

        self.pushButton_next_date = QPushButton(self.frame_daily_intake_buttons)
        self.pushButton_next_date.setObjectName(u"pushButton_next_date")
        self.pushButton_next_date.setMinimumSize(QSize(30, 30))
        self.pushButton_next_date.setMaximumSize(QSize(30, 30))

        self.horizontalLayout_2.addWidget(self.pushButton_next_date)

        self.pushButton_calendar_toggle = QPushButton(self.frame_daily_intake_buttons)
        self.pushButton_calendar_toggle.setObjectName(u"pushButton_calendar_toggle")
        self.pushButton_calendar_toggle.setMinimumSize(QSize(30, 30))
        self.pushButton_calendar_toggle.setMaximumSize(QSize(30, 30))
        self.pushButton_calendar_toggle.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.pushButton_calendar_toggle)


        self.verticalLayout_frame_dashboard_right.addWidget(self.frame_daily_intake_buttons, 0, Qt.AlignLeft)


        self.horizontalLayout_dashboard.addWidget(self.frame_dashboard_right, 0, Qt.AlignTop)

        self.stackedWidget_main.addWidget(self.page_daily_intake)
        self.page_catalogue = QWidget()
        self.page_catalogue.setObjectName(u"page_catalogue")
        self.verticalLayout_catalogue = QVBoxLayout(self.page_catalogue)
        self.verticalLayout_catalogue.setSpacing(0)
        self.verticalLayout_catalogue.setObjectName(u"verticalLayout_catalogue")
        self.verticalLayout_catalogue.setContentsMargins(0, 0, 0, 0)
        self.frame_catalogue_options = QFrame(self.page_catalogue)
        self.frame_catalogue_options.setObjectName(u"frame_catalogue_options")
        self.frame_catalogue_options.setFrameShape(QFrame.NoFrame)
        self.frame_catalogue_options.setFrameShadow(QFrame.Plain)
        self.frame_catalogue_options.setLineWidth(0)
        self.horizontalLayout = QHBoxLayout(self.frame_catalogue_options)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_4 = QLabel(self.frame_catalogue_options)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(0, 25))
        self.label_4.setMaximumSize(QSize(16777215, 25))

        self.horizontalLayout.addWidget(self.label_4)

        self.lineEdit_catalogue_search = QLineEdit(self.frame_catalogue_options)
        self.lineEdit_catalogue_search.setObjectName(u"lineEdit_catalogue_search")
        self.lineEdit_catalogue_search.setMinimumSize(QSize(120, 25))
        self.lineEdit_catalogue_search.setMaximumSize(QSize(120, 25))

        self.horizontalLayout.addWidget(self.lineEdit_catalogue_search)

        self.pushButton_clear_catalogue_search = QPushButton(self.frame_catalogue_options)
        self.pushButton_clear_catalogue_search.setObjectName(u"pushButton_clear_catalogue_search")
        self.pushButton_clear_catalogue_search.setMinimumSize(QSize(30, 30))
        self.pushButton_clear_catalogue_search.setMaximumSize(QSize(30, 30))

        self.horizontalLayout.addWidget(self.pushButton_clear_catalogue_search)


        self.verticalLayout_catalogue.addWidget(self.frame_catalogue_options, 0, Qt.AlignLeft|Qt.AlignTop)

        self.frame_catalogue = QFrame(self.page_catalogue)
        self.frame_catalogue.setObjectName(u"frame_catalogue")
        self.frame_catalogue.setFrameShape(QFrame.NoFrame)
        self.frame_catalogue.setFrameShadow(QFrame.Plain)
        self.frame_catalogue.setLineWidth(0)
        self.verticalLayout_frame_catalogue = QVBoxLayout(self.frame_catalogue)
        self.verticalLayout_frame_catalogue.setSpacing(0)
        self.verticalLayout_frame_catalogue.setObjectName(u"verticalLayout_frame_catalogue")
        self.verticalLayout_frame_catalogue.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_catalogue.addWidget(self.frame_catalogue)

        self.stackedWidget_main.addWidget(self.page_catalogue)
        self.page_recipes = QWidget()
        self.page_recipes.setObjectName(u"page_recipes")
        self.verticalLayout_4 = QVBoxLayout(self.page_recipes)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.frame_recipes = QFrame(self.page_recipes)
        self.frame_recipes.setObjectName(u"frame_recipes")
        self.frame_recipes.setFrameShape(QFrame.NoFrame)
        self.frame_recipes.setFrameShadow(QFrame.Plain)
        self.frame_recipes.setLineWidth(0)
        self.horizontalLayout_recipe_frames = QHBoxLayout(self.frame_recipes)
        self.horizontalLayout_recipe_frames.setSpacing(0)
        self.horizontalLayout_recipe_frames.setObjectName(u"horizontalLayout_recipe_frames")
        self.horizontalLayout_recipe_frames.setContentsMargins(0, 0, 0, 0)
        self.frame_recipes_list = QFrame(self.frame_recipes)
        self.frame_recipes_list.setObjectName(u"frame_recipes_list")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_recipes_list.sizePolicy().hasHeightForWidth())
        self.frame_recipes_list.setSizePolicy(sizePolicy1)
        self.frame_recipes_list.setMinimumSize(QSize(0, 0))
        self.frame_recipes_list.setMaximumSize(QSize(16777215, 16777215))
        self.frame_recipes_list.setFrameShape(QFrame.NoFrame)
        self.frame_recipes_list.setFrameShadow(QFrame.Plain)
        self.frame_recipes_list.setLineWidth(0)
        self.verticalLayout_frame_recipes_list = QVBoxLayout(self.frame_recipes_list)
        self.verticalLayout_frame_recipes_list.setSpacing(0)
        self.verticalLayout_frame_recipes_list.setObjectName(u"verticalLayout_frame_recipes_list")
        self.verticalLayout_frame_recipes_list.setContentsMargins(0, 0, 0, 0)
        self.frame_recipe_list_search = QFrame(self.frame_recipes_list)
        self.frame_recipe_list_search.setObjectName(u"frame_recipe_list_search")
        self.frame_recipe_list_search.setFrameShape(QFrame.NoFrame)
        self.frame_recipe_list_search.setFrameShadow(QFrame.Plain)
        self.frame_recipe_list_search.setLineWidth(0)
        self.horizontalLayout_frame_recipe_list_search = QHBoxLayout(self.frame_recipe_list_search)
        self.horizontalLayout_frame_recipe_list_search.setObjectName(u"horizontalLayout_frame_recipe_list_search")
        self.label_recipe_list_search = QLabel(self.frame_recipe_list_search)
        self.label_recipe_list_search.setObjectName(u"label_recipe_list_search")
        self.label_recipe_list_search.setMinimumSize(QSize(0, 25))
        self.label_recipe_list_search.setMaximumSize(QSize(16777215, 25))

        self.horizontalLayout_frame_recipe_list_search.addWidget(self.label_recipe_list_search)

        self.lineEdit_recipe_list_search = QLineEdit(self.frame_recipe_list_search)
        self.lineEdit_recipe_list_search.setObjectName(u"lineEdit_recipe_list_search")
        self.lineEdit_recipe_list_search.setMinimumSize(QSize(120, 25))
        self.lineEdit_recipe_list_search.setMaximumSize(QSize(120, 25))

        self.horizontalLayout_frame_recipe_list_search.addWidget(self.lineEdit_recipe_list_search)

        self.pushButton_clear_recipe_list_search = QPushButton(self.frame_recipe_list_search)
        self.pushButton_clear_recipe_list_search.setObjectName(u"pushButton_clear_recipe_list_search")
        self.pushButton_clear_recipe_list_search.setMinimumSize(QSize(30, 30))
        self.pushButton_clear_recipe_list_search.setMaximumSize(QSize(30, 30))

        self.horizontalLayout_frame_recipe_list_search.addWidget(self.pushButton_clear_recipe_list_search)


        self.verticalLayout_frame_recipes_list.addWidget(self.frame_recipe_list_search, 0, Qt.AlignLeft|Qt.AlignTop)


        self.horizontalLayout_recipe_frames.addWidget(self.frame_recipes_list)

        self.frame_recipes_tables = QFrame(self.frame_recipes)
        self.frame_recipes_tables.setObjectName(u"frame_recipes_tables")
        self.frame_recipes_tables.setFrameShape(QFrame.NoFrame)
        self.frame_recipes_tables.setFrameShadow(QFrame.Plain)
        self.frame_recipes_tables.setLineWidth(0)
        self.verticalLayout_frame_recipes_tables = QVBoxLayout(self.frame_recipes_tables)
        self.verticalLayout_frame_recipes_tables.setSpacing(6)
        self.verticalLayout_frame_recipes_tables.setObjectName(u"verticalLayout_frame_recipes_tables")
        self.verticalLayout_frame_recipes_tables.setContentsMargins(0, 0, 0, 0)
        self.frame_recipe_data_table = QFrame(self.frame_recipes_tables)
        self.frame_recipe_data_table.setObjectName(u"frame_recipe_data_table")
        sizePolicy1.setHeightForWidth(self.frame_recipe_data_table.sizePolicy().hasHeightForWidth())
        self.frame_recipe_data_table.setSizePolicy(sizePolicy1)
        self.frame_recipe_data_table.setMinimumSize(QSize(0, 0))
        self.frame_recipe_data_table.setBaseSize(QSize(0, 0))
        self.frame_recipe_data_table.setFrameShape(QFrame.NoFrame)
        self.frame_recipe_data_table.setFrameShadow(QFrame.Plain)
        self.frame_recipe_data_table.setLineWidth(0)
        self.verticalLayout_frame_recipe_data_table = QVBoxLayout(self.frame_recipe_data_table)
        self.verticalLayout_frame_recipe_data_table.setSpacing(0)
        self.verticalLayout_frame_recipe_data_table.setObjectName(u"verticalLayout_frame_recipe_data_table")
        self.verticalLayout_frame_recipe_data_table.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_frame_recipes_tables.addWidget(self.frame_recipe_data_table)

        self.frame_recipe_details = QFrame(self.frame_recipes_tables)
        self.frame_recipe_details.setObjectName(u"frame_recipe_details")
        sizePolicy1.setHeightForWidth(self.frame_recipe_details.sizePolicy().hasHeightForWidth())
        self.frame_recipe_details.setSizePolicy(sizePolicy1)
        self.frame_recipe_details.setFrameShape(QFrame.StyledPanel)
        self.frame_recipe_details.setFrameShadow(QFrame.Raised)
        self.frame_recipe_details.setLineWidth(1)
        self.verticalLayout_2 = QVBoxLayout(self.frame_recipe_details)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_selected_recipe_identifier = QLabel(self.frame_recipe_details)
        self.label_selected_recipe_identifier.setObjectName(u"label_selected_recipe_identifier")
        self.label_selected_recipe_identifier.setMinimumSize(QSize(0, 30))
        self.label_selected_recipe_identifier.setMaximumSize(QSize(16777215, 30))

        self.verticalLayout_2.addWidget(self.label_selected_recipe_identifier)

        self.frame_recipe_description = QFrame(self.frame_recipe_details)
        self.frame_recipe_description.setObjectName(u"frame_recipe_description")
        self.frame_recipe_description.setFrameShape(QFrame.NoFrame)
        self.frame_recipe_description.setFrameShadow(QFrame.Plain)
        self.frame_recipe_description.setLineWidth(0)
        self.verticalLayout_frame_recipe_description = QVBoxLayout(self.frame_recipe_description)
        self.verticalLayout_frame_recipe_description.setSpacing(0)
        self.verticalLayout_frame_recipe_description.setObjectName(u"verticalLayout_frame_recipe_description")
        self.verticalLayout_frame_recipe_description.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_2.addWidget(self.frame_recipe_description)

        self.groupBox_measured_mass = QGroupBox(self.frame_recipe_details)
        self.groupBox_measured_mass.setObjectName(u"groupBox_measured_mass")
        self.groupBox_measured_mass.setMinimumSize(QSize(0, 0))
        self.groupBox_measured_mass.setCheckable(True)
        self.verticalLayout_groupbox_mass_inputs = QVBoxLayout(self.groupBox_measured_mass)
        self.verticalLayout_groupbox_mass_inputs.setSpacing(0)
        self.verticalLayout_groupbox_mass_inputs.setObjectName(u"verticalLayout_groupbox_mass_inputs")
        self.verticalLayout_groupbox_mass_inputs.setContentsMargins(0, 10, 0, 10)
        self.frame_measured_mass_inputs = QFrame(self.groupBox_measured_mass)
        self.frame_measured_mass_inputs.setObjectName(u"frame_measured_mass_inputs")
        self.frame_measured_mass_inputs.setFrameShape(QFrame.NoFrame)
        self.frame_measured_mass_inputs.setFrameShadow(QFrame.Plain)
        self.frame_measured_mass_inputs.setLineWidth(0)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_measured_mass_inputs)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.frame_net_mass_inputs = QFrame(self.frame_measured_mass_inputs)
        self.frame_net_mass_inputs.setObjectName(u"frame_net_mass_inputs")
        self.frame_net_mass_inputs.setFrameShape(QFrame.NoFrame)
        self.frame_net_mass_inputs.setFrameShadow(QFrame.Plain)
        self.frame_net_mass_inputs.setLineWidth(0)
        self.gridLayout = QGridLayout(self.frame_net_mass_inputs)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.doubleSpinBox_recipe_measured_mass = QDoubleSpinBox(self.frame_net_mass_inputs)
        self.doubleSpinBox_recipe_measured_mass.setObjectName(u"doubleSpinBox_recipe_measured_mass")
        self.doubleSpinBox_recipe_measured_mass.setMinimumSize(QSize(0, 25))
        self.doubleSpinBox_recipe_measured_mass.setMaximumSize(QSize(100, 25))
        self.doubleSpinBox_recipe_measured_mass.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_recipe_measured_mass.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_recipe_measured_mass.setDecimals(0)
        self.doubleSpinBox_recipe_measured_mass.setMaximum(9999.000000000000000)
        self.doubleSpinBox_recipe_measured_mass.setSingleStep(0.000000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_recipe_measured_mass, 0, 1, 1, 1)

        self.label_measured_mass = QLabel(self.frame_net_mass_inputs)
        self.label_measured_mass.setObjectName(u"label_measured_mass")
        self.label_measured_mass.setMinimumSize(QSize(0, 25))
        self.label_measured_mass.setMaximumSize(QSize(120, 25))

        self.gridLayout.addWidget(self.label_measured_mass, 0, 0, 1, 1)

        self.label_mass_reduction = QLabel(self.frame_net_mass_inputs)
        self.label_mass_reduction.setObjectName(u"label_mass_reduction")
        self.label_mass_reduction.setMinimumSize(QSize(0, 25))
        self.label_mass_reduction.setMaximumSize(QSize(120, 25))

        self.gridLayout.addWidget(self.label_mass_reduction, 1, 0, 1, 1)

        self.doubleSpinBox_mass_reduction = QDoubleSpinBox(self.frame_net_mass_inputs)
        self.doubleSpinBox_mass_reduction.setObjectName(u"doubleSpinBox_mass_reduction")
        self.doubleSpinBox_mass_reduction.setMinimumSize(QSize(0, 25))
        self.doubleSpinBox_mass_reduction.setMaximumSize(QSize(100, 25))
        self.doubleSpinBox_mass_reduction.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_mass_reduction.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_mass_reduction.setDecimals(0)
        self.doubleSpinBox_mass_reduction.setMaximum(9999.000000000000000)
        self.doubleSpinBox_mass_reduction.setSingleStep(0.000000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_mass_reduction, 1, 1, 1, 1)

        self.label_mass_reduction_unit = QLabel(self.frame_net_mass_inputs)
        self.label_mass_reduction_unit.setObjectName(u"label_mass_reduction_unit")
        self.label_mass_reduction_unit.setMinimumSize(QSize(30, 25))
        self.label_mass_reduction_unit.setMaximumSize(QSize(30, 25))

        self.gridLayout.addWidget(self.label_mass_reduction_unit, 1, 2, 1, 1)

        self.label_measured_mass_unit = QLabel(self.frame_net_mass_inputs)
        self.label_measured_mass_unit.setObjectName(u"label_measured_mass_unit")
        self.label_measured_mass_unit.setMinimumSize(QSize(30, 25))
        self.label_measured_mass_unit.setMaximumSize(QSize(30, 25))

        self.gridLayout.addWidget(self.label_measured_mass_unit, 0, 2, 1, 1)


        self.horizontalLayout_3.addWidget(self.frame_net_mass_inputs)

        self.frame_net_amount_summary = QFrame(self.frame_measured_mass_inputs)
        self.frame_net_amount_summary.setObjectName(u"frame_net_amount_summary")
        self.frame_net_amount_summary.setFrameShape(QFrame.NoFrame)
        self.frame_net_amount_summary.setFrameShadow(QFrame.Plain)
        self.frame_net_amount_summary.setLineWidth(0)
        self.gridLayout_4 = QGridLayout(self.frame_net_amount_summary)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_mass_reduction_2 = QLabel(self.frame_net_amount_summary)
        self.label_mass_reduction_2.setObjectName(u"label_mass_reduction_2")
        self.label_mass_reduction_2.setMinimumSize(QSize(0, 25))
        self.label_mass_reduction_2.setMaximumSize(QSize(120, 25))

        self.gridLayout_4.addWidget(self.label_mass_reduction_2, 0, 0, 1, 1)

        self.doubleSpinBox_net_mass_total = QDoubleSpinBox(self.frame_net_amount_summary)
        self.doubleSpinBox_net_mass_total.setObjectName(u"doubleSpinBox_net_mass_total")
        self.doubleSpinBox_net_mass_total.setEnabled(False)
        self.doubleSpinBox_net_mass_total.setMinimumSize(QSize(0, 25))
        self.doubleSpinBox_net_mass_total.setMaximumSize(QSize(100, 25))
        self.doubleSpinBox_net_mass_total.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_net_mass_total.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_net_mass_total.setDecimals(0)
        self.doubleSpinBox_net_mass_total.setMaximum(9999.000000000000000)
        self.doubleSpinBox_net_mass_total.setSingleStep(0.000000000000000)

        self.gridLayout_4.addWidget(self.doubleSpinBox_net_mass_total, 0, 1, 1, 1)

        self.label_mass_reduction_unit_2 = QLabel(self.frame_net_amount_summary)
        self.label_mass_reduction_unit_2.setObjectName(u"label_mass_reduction_unit_2")
        self.label_mass_reduction_unit_2.setMinimumSize(QSize(30, 25))
        self.label_mass_reduction_unit_2.setMaximumSize(QSize(30, 25))

        self.gridLayout_4.addWidget(self.label_mass_reduction_unit_2, 0, 2, 1, 1)

        self.label_mass_reduction_3 = QLabel(self.frame_net_amount_summary)
        self.label_mass_reduction_3.setObjectName(u"label_mass_reduction_3")
        self.label_mass_reduction_3.setMinimumSize(QSize(0, 25))
        self.label_mass_reduction_3.setMaximumSize(QSize(120, 25))

        self.gridLayout_4.addWidget(self.label_mass_reduction_3, 1, 0, 1, 1)

        self.doubleSpinBox_mass_ratio = QDoubleSpinBox(self.frame_net_amount_summary)
        self.doubleSpinBox_mass_ratio.setObjectName(u"doubleSpinBox_mass_ratio")
        self.doubleSpinBox_mass_ratio.setEnabled(False)
        self.doubleSpinBox_mass_ratio.setMinimumSize(QSize(0, 25))
        self.doubleSpinBox_mass_ratio.setMaximumSize(QSize(100, 25))
        self.doubleSpinBox_mass_ratio.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_mass_ratio.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_mass_ratio.setDecimals(3)
        self.doubleSpinBox_mass_ratio.setMaximum(9999.000000000000000)
        self.doubleSpinBox_mass_ratio.setSingleStep(0.000000000000000)

        self.gridLayout_4.addWidget(self.doubleSpinBox_mass_ratio, 1, 1, 1, 1)

        self.label_mass_reduction_unit_3 = QLabel(self.frame_net_amount_summary)
        self.label_mass_reduction_unit_3.setObjectName(u"label_mass_reduction_unit_3")
        self.label_mass_reduction_unit_3.setMinimumSize(QSize(30, 25))
        self.label_mass_reduction_unit_3.setMaximumSize(QSize(30, 25))

        self.gridLayout_4.addWidget(self.label_mass_reduction_unit_3, 1, 2, 1, 1)


        self.horizontalLayout_3.addWidget(self.frame_net_amount_summary)


        self.verticalLayout_groupbox_mass_inputs.addWidget(self.frame_measured_mass_inputs, 0, Qt.AlignLeft|Qt.AlignTop)


        self.verticalLayout_2.addWidget(self.groupBox_measured_mass)


        self.verticalLayout_frame_recipes_tables.addWidget(self.frame_recipe_details)


        self.horizontalLayout_recipe_frames.addWidget(self.frame_recipes_tables)

        self.frame_ingredient_details = QFrame(self.frame_recipes)
        self.frame_ingredient_details.setObjectName(u"frame_ingredient_details")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_ingredient_details.sizePolicy().hasHeightForWidth())
        self.frame_ingredient_details.setSizePolicy(sizePolicy2)
        self.frame_ingredient_details.setMinimumSize(QSize(0, 0))
        self.frame_ingredient_details.setFrameShape(QFrame.StyledPanel)
        self.frame_ingredient_details.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame_ingredient_details)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.frame_ingredient_definition = QFrame(self.frame_ingredient_details)
        self.frame_ingredient_definition.setObjectName(u"frame_ingredient_definition")
        self.frame_ingredient_definition.setFrameShape(QFrame.NoFrame)
        self.frame_ingredient_definition.setFrameShadow(QFrame.Plain)
        self.frame_ingredient_definition.setLineWidth(0)
        self.verticalLayout_6 = QVBoxLayout(self.frame_ingredient_definition)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_selected_ingredient_identifier = QLabel(self.frame_ingredient_definition)
        self.label_selected_ingredient_identifier.setObjectName(u"label_selected_ingredient_identifier")
        self.label_selected_ingredient_identifier.setMinimumSize(QSize(0, 25))
        self.label_selected_ingredient_identifier.setMaximumSize(QSize(16777215, 25))

        self.verticalLayout_6.addWidget(self.label_selected_ingredient_identifier)

        self.groupBox = QGroupBox(self.frame_ingredient_definition)
        self.groupBox.setObjectName(u"groupBox")
        self.gridLayout_2 = QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.comboBox_ingredient_amount_definition = QComboBox(self.groupBox)
        self.comboBox_ingredient_amount_definition.setObjectName(u"comboBox_ingredient_amount_definition")
        self.comboBox_ingredient_amount_definition.setMinimumSize(QSize(250, 25))
        self.comboBox_ingredient_amount_definition.setMaximumSize(QSize(16777215, 25))

        self.gridLayout_2.addWidget(self.comboBox_ingredient_amount_definition, 0, 0, 1, 2)

        self.comboBox_relative_amount_ingredient = QComboBox(self.groupBox)
        self.comboBox_relative_amount_ingredient.setObjectName(u"comboBox_relative_amount_ingredient")
        self.comboBox_relative_amount_ingredient.setMinimumSize(QSize(0, 25))
        self.comboBox_relative_amount_ingredient.setMaximumSize(QSize(16777215, 25))

        self.gridLayout_2.addWidget(self.comboBox_relative_amount_ingredient, 1, 1, 1, 1)

        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)
        self.label.setMinimumSize(QSize(80, 25))
        self.label.setMaximumSize(QSize(80, 25))

        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)


        self.verticalLayout_6.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.frame_ingredient_definition)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.gridLayout_3 = QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.comboBox_ingredient_net_amount_definition = QComboBox(self.groupBox_2)
        self.comboBox_ingredient_net_amount_definition.setObjectName(u"comboBox_ingredient_net_amount_definition")
        self.comboBox_ingredient_net_amount_definition.setMinimumSize(QSize(250, 25))
        self.comboBox_ingredient_net_amount_definition.setMaximumSize(QSize(16777215, 25))

        self.gridLayout_3.addWidget(self.comboBox_ingredient_net_amount_definition, 0, 0, 1, 2)


        self.verticalLayout_6.addWidget(self.groupBox_2)


        self.verticalLayout_5.addWidget(self.frame_ingredient_definition, 0, Qt.AlignTop)


        self.horizontalLayout_recipe_frames.addWidget(self.frame_ingredient_details)


        self.verticalLayout_4.addWidget(self.frame_recipes)

        self.stackedWidget_main.addWidget(self.page_recipes)

        self.verticalLayout.addWidget(self.stackedWidget_main)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1045, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuTheme = QMenu(self.menuView)
        self.menuTheme.setObjectName(u"menuTheme")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuExport = QMenu(self.menuTools)
        self.menuExport.setObjectName(u"menuExport")
        self.menuImport = QMenu(self.menuTools)
        self.menuImport.setObjectName(u"menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_file = QToolBar(MainWindow)
        self.toolBar_file.setObjectName(u"toolBar_file")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar_file)
        self.toolBar_navigation = QToolBar(MainWindow)
        self.toolBar_navigation.setObjectName(u"toolBar_navigation")
        self.toolBar_navigation.setOrientation(Qt.Vertical)
        MainWindow.addToolBar(Qt.ToolBarArea.LeftToolBarArea, self.toolBar_navigation)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.action_menubar_open)
        self.menuFile.addAction(self.action_menubar_save)
        self.menuFile.addAction(self.action_menubar_save_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_menubar_quit)
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuTheme.addAction(self.action_theme_light)
        self.menuTheme.addAction(self.action_theme_dark)
        self.menuTheme.addAction(self.action_theme_fusion)
        self.menuTools.addAction(self.menuExport.menuAction())
        self.menuTools.addAction(self.menuImport.menuAction())
        self.menuExport.addAction(self.action_export_daily_intake)
        self.menuExport.addAction(self.action_export_catalogue)
        self.menuExport.addAction(self.action_export_recipes)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.action_export_Excel_catalogue)
        self.menuImport.addAction(self.action_import_daily_intake)
        self.menuImport.addAction(self.action_import_catalogue)
        self.menuImport.addAction(self.action_import_recipes)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.action_import_Excel_catalogue)
        self.toolBar_file.addAction(self.actionOpen)
        self.toolBar_file.addAction(self.actionSave)
        self.toolBar_navigation.addAction(self.action_daily_intake)
        self.toolBar_navigation.addAction(self.action_catalogue)
        self.toolBar_navigation.addAction(self.action_recipes)

        self.retranslateUi(MainWindow)

        self.stackedWidget_main.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_theme_light.setText(QCoreApplication.translate("MainWindow", u"Light", None))
        self.action_theme_dark.setText(QCoreApplication.translate("MainWindow", u"Dark", None))
        self.action_theme_fusion.setText(QCoreApplication.translate("MainWindow", u"Fusion", None))
        self.action_catalogue.setText(QCoreApplication.translate("MainWindow", u"Catalogue", None))
        self.action_recipes.setText(QCoreApplication.translate("MainWindow", u"Recipes", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.action_daily_intake.setText(QCoreApplication.translate("MainWindow", u"Daily Intake", None))
        self.action_menubar_open.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        self.action_menubar_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.action_export_catalogue.setText(QCoreApplication.translate("MainWindow", u"Catalogue (.ctc)...", None))
        self.action_import_catalogue.setText(QCoreApplication.translate("MainWindow", u"Catalogue (.ctc)...", None))
        self.action_export_recipes.setText(QCoreApplication.translate("MainWindow", u"Recipes (.ctr)...", None))
        self.action_import_recipes.setText(QCoreApplication.translate("MainWindow", u"Recipes (.ctr)...", None))
        self.action_menubar_save_as.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.action_menubar_quit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.action_export_daily_intake.setText(QCoreApplication.translate("MainWindow", u"Daily Intake (.ctd)...", None))
        self.action_import_daily_intake.setText(QCoreApplication.translate("MainWindow", u"Daily Intake (.ctd)...", None))
        self.action_import_Excel_catalogue.setText(QCoreApplication.translate("MainWindow", u"Catalogue (.xlsx)...", None))
        self.action_export_Excel_catalogue.setText(QCoreApplication.translate("MainWindow", u"Catalogue (.xlsx)...", None))
        self.label_nutrition_targets.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Nutrition Targets</span></p></body></html>", None))
        self.pushButton_add_catalogue_item.setText("")
        self.pushButton_add_recipe_item.setText("")
        self.pushButton_previous_date.setText("")
        self.pushButton_next_date.setText("")
        self.pushButton_calendar_toggle.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.pushButton_clear_catalogue_search.setText("")
        self.label_recipe_list_search.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.pushButton_clear_recipe_list_search.setText("")
        self.label_selected_recipe_identifier.setText(QCoreApplication.translate("MainWindow", u"Recipe Identifier", None))
        self.groupBox_measured_mass.setTitle(QCoreApplication.translate("MainWindow", u"Use Measured Mass Calculation", None))
        self.label_measured_mass.setText(QCoreApplication.translate("MainWindow", u"Measured Mass", None))
        self.label_mass_reduction.setText(QCoreApplication.translate("MainWindow", u"Reduction", None))
        self.label_mass_reduction_unit.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_measured_mass_unit.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_mass_reduction_2.setText(QCoreApplication.translate("MainWindow", u"Net Mass", None))
        self.label_mass_reduction_unit_2.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_mass_reduction_3.setText(QCoreApplication.translate("MainWindow", u"Ratio", None))
        self.label_mass_reduction_unit_3.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_selected_ingredient_identifier.setText(QCoreApplication.translate("MainWindow", u"Ingredient:   /", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Amount Definition", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Relative To:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Net Amount Definition", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"Export", None))
        self.menuImport.setTitle(QCoreApplication.translate("MainWindow", u"Import", None))
        self.toolBar_file.setWindowTitle(QCoreApplication.translate("MainWindow", u"File Toolbar", None))
        self.toolBar_navigation.setWindowTitle(QCoreApplication.translate("MainWindow", u"Navigation Toolbar", None))
    # retranslateUi

